---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/handpoint/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .osx
  - .tmux.conf

homebrew_installed_packages:
  - curl
  - packer  
  - git
  - java11
  - maven
  - awscli
  - awslogs
  - bash-completion
  - httpie
  - iperf
  - node
  - n
  - cowsay
  - wget
  - wrk
  - tfswitch
  - postgresql@11
  - fastlane
  - hub
  - yarn
  - tmux

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - warrensbox/tap
  - petere/postgresql
  - adoptopenjdk/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - sublime-text
  - pycharm
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - slack
  - transmit
  - android-studio
  - wireshark
  - pgadmin4
  - intellij-idea
  - openoffice
  - adoptopenjdk8
  - netnewswire
  - android-platform-tools

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: 
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
  - name: ionic 
    version: 5.4.16
  - name: cordova 
    version: 8.0.0
  - name: protractor
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
