---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/handpoint/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .osx
  - .tmux.conf

homebrew_installed_packages:
  - curl
  - packer  
  - git
  - java11
  - maven
  - awscli
  - awslogs
  - bash-completion
  - httpie
  - iperf
  - node
  - n
  - cowsay
  - wget
  - wrk
  - terraform
  - tfswitch
  - postgresql@11
  - fastlane
  - hub
  - yarn
  - tmux
  - cocoapods
  - jq

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - warrensbox/tap
  - petere/postgresql
  - adoptopenjdk/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - sublime-text
  - pycharm
  - chromedriver
  - dropbox
  - firefox
  - google-chrome
  - slack
  - cyberduck
  - android-studio
  - wireshark
  - pgadmin4
  - intellij-idea
  - openoffice
  - adoptopenjdk8
  - netnewswire
  - android-platform-tools
  - gimp
  - github

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

composer_packages:
  - name: hirak/prestissimo
  - name: drush/drush
    version: '^8.1'

gem_packages:
  - name: bundler
    state: latest

npm_packages:
  - cordova@8.0.0
  - nodemon
  - ionic@5.4.16

pip_packages:
  - name: mkdocs

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
